volumes:
  pyaleph-postgres:
  pyaleph-rabbitmq:
  pyaleph-redis:
  pyaleph-ipfs:

services:
  pyaleph:
    restart: always
    image: ${PYALEPH_IMAGE}:${PYALEPH_TAG}
    command: --config /opt/pyaleph/config.yml --key-dir /opt/pyaleph/keys -v
    volumes:
      - ./config.yml:/opt/pyaleph/config.yml:ro
      - /etc/pyaleph/keys:/opt/pyaleph/keys
      - /var/lib/pyaleph:/var/lib/pyaleph
    depends_on:
      - postgres
      - ipfs
      - p2p-service
      - redis
      - anvil
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  pyaleph-api:
    restart: always
    image: ${PYALEPH_IMAGE}:${PYALEPH_TAG}
    command: --config /opt/pyaleph/config.yml --key-dir /opt/pyaleph/keys -v
    entrypoint: ["bash", "deployment/scripts/run_aleph_ccn_api.sh"]
    ports:
      - "4024:4024/tcp"
    volumes:
      - ./config.yml:/opt/pyaleph/config.yml:ro
      - /var/lib/pyaleph:/var/lib/pyaleph
    environment:
      CCN_CONFIG_API_PORT: 4024
      CCN_CONFIG_API_NB_WORKERS: 4
    depends_on:
      - pyaleph
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  p2p-service:
    restart: always
    image: ${P2P_SERVICE_IMAGE}:${P2P_SERVICE_TAG}
    networks:
      - pyaleph
    volumes:
      - ./config.yml:/etc/p2p-service/config.yml:ro
      - /etc/pyaleph/keys/node-secret.pkcs8.der:/etc/p2p-service/node-secret.pkcs8.der:ro
    depends_on:
      - rabbitmq
    environment:
      RUST_LOG: info
    ports:
      - "4025:4025"
      - "127.0.0.1:4030:4030"
    command:
      - "--config"
      - "/etc/p2p-service/config.yml"
      - "--private-key-file"
      - "/etc/p2p-service/node-secret.pkcs8.der"

  postgres:
    restart: always
    image: ${POSTGRES_IMAGE}:${POSTGRES_TAG}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pyaleph-postgres:/var/lib/postgresql/data
      - ./001-create-scheduler-db.sql:/docker-entrypoint-initdb.d/001-create-scheduler-db.sql:ro
    environment:
      POSTGRES_USER: aleph
      POSTGRES_PASSWORD: decentralize-everything
      POSTGRES_DB: aleph
    networks:
      - pyaleph
    shm_size: "2gb"

  rabbitmq:
    restart: always
    image: ${RABBITMQ_IMAGE}:${RABBITMQ_TAG}
    networks:
      - pyaleph
    environment:
      RABBITMQ_DEFAULT_USER: aleph-p2p
      RABBITMQ_DEFAULT_PASS: change-me!
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - pyaleph-rabbitmq:/var/lib/rabbitmq

  redis:
    restart: always
    image: ${REDIS_IMAGE}:${REDIS_TAG}
    networks:
      - pyaleph
    volumes:
      - pyaleph-redis:/data

  ipfs:
    restart: always
    image: ${IPFS_IMAGE}:${IPFS_TAG}
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
    volumes:
      - pyaleph-ipfs:/data/ipfs
      - ./001-update-ipfs-config.sh:/container-init.d/001-update-ipfs-config.sh:ro
    environment:
      - IPFS_PROFILE=server
      - IPFS_TELEMETRY=off
    networks:
      - pyaleph
    command: ["daemon", "--enable-pubsub-experiment", "--enable-gc", "--migrate"]

  anvil:
    restart: always
    image: ${ANVIL_IMAGE}:${ANVIL_TAG}
    networks:
      - pyaleph
    entrypoint: ["anvil", "--host", "0.0.0.0", "--port", "8545", "--code-size-limit", "100000"]

  indexer:
    restart: always
    image: ${INDEXER_IMAGE}:${INDEXER_TAG}
    environment:
      INDEXER: aleph-credit
      INDEXER_BLOCKCHAINS: ethereum
      INDEXER_MIN_BLOCK_HEIGHT: "0"
      INDEXER_API_PORT: "8081"
      INDEXER_NAMESPACE: aleph-credit
      INDEXER_CHAINS_CONFIG: /config/chains.yaml
      ETHEREUM_RPC: http://anvil:8545
      ETHEREUM_EXPLORER_URL: "http://localhost:0"
      ALEPH_HOST: http://pyaleph-api:4024
      ALEPH_PAYMENT_CHANNEL: ALEPH_TESTNET_CREDIT
      ALEPH_PAYMENT_ADDRESS: ${CREDIT_SENDER_ADDRESS}
    volumes:
      - ./indexer/chains.yaml:/config/chains.yaml:ro
      - ./indexer/abis:/app/config/abis:ro
    ports:
      - "127.0.0.1:8081:8081"
    depends_on:
      - anvil
      - pyaleph-api
    profiles:
      - credits
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  credit-service:
    restart: always
    image: ${CREDIT_SERVICE_IMAGE}:${CREDIT_SERVICE_TAG}
    environment:
      ALEPH_SENDER_PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      ALEPH_CREDIT_ADDRESS: ${CREDIT_SENDER_ADDRESS}
      ALEPH_HOST: http://pyaleph-api:4024
      ALEPH_PAYMENT_CHANNEL: ALEPH_TESTNET_CREDIT
      INDEXER_HOST: http://indexer:8081
      PAYMENTS_ENV: staging
      BLOCKCHAIN_ID: ethereum
      TOKEN_USDC_ADDRESS: ${USDALEPH_ADDRESS}
      TOKEN_USDC_DECIMALS: "6"
      TOKEN_ALEPH_ADDRESS: ${MOCKALEPH_ADDRESS}
      WEB3_ETHEREUM_TESTNET_RPC_HOST: http://anvil:8545
      WEB3_ETHEREUM_TESTNET_CONTRACT: ${CREDIT_CONTRACT_ADDRESS}
      DISTRIBUTION_START_DATE: ${DISTRIBUTION_START_DATE}
      JOB_PAYMENT_ENABLED: "false"
      JOB_EXPENSE_ENABLED: "false"
      LOG_LEVEL: debug
    depends_on:
      - indexer
      - pyaleph-api
    profiles:
      - credits
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  nodestatus:
    restart: always
    image: alephim/nodestatus:latest
    command: nodestatus -vv --window-size 365d
    environment:
      ETHEREUM_API_SERVER: http://anvil:8545
      ETHEREUM_TOKEN_CONTRACT: ${MOCKALEPH_ADDRESS}
      ETHEREUM_CHAIN_ID: "31337"
      ETHEREUM_MIN_HEIGHT: "0"
      ETHEREUM_TOTAL_SUPPLY: "0"
      ETHEREUM_DEPLOYER: "0x0000000000000000000000000000000000000000"
      ETHEREUM_DECIMALS: "18"
      ETHEREUM_PKEY: "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
      ALEPH_API_SERVER: http://pyaleph-api:4024
      ALEPH_CHANNEL: TEST
      FILTER_TAG: mainnet
      DB_PATH: /data/database
      BALANCES_SENDERS: '["0x70997970C51812dc3A010C7d01b50e0d17dc79C8"]'
      SCORES_SENDERS: '["0x70997970C51812dc3A010C7d01b50e0d17dc79C8"]'
      STATUS_SENDER: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    depends_on:
      - anvil
      - pyaleph-api
    profiles:
      - nodestatus
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  nodestatus-balances:
    restart: always
    image: alephim/nodestatus:latest
    command: monitor-balances -vv
    environment:
      ETHEREUM_API_SERVER: http://anvil:8545
      ETHEREUM_TOKEN_CONTRACT: ${MOCKALEPH_ADDRESS}
      ETHEREUM_CHAIN_ID: "31337"
      ETHEREUM_MIN_HEIGHT: "0"
      ETHEREUM_TOTAL_SUPPLY: "0"
      ETHEREUM_DEPLOYER: "0x0000000000000000000000000000000000000000"
      ETHEREUM_DECIMALS: "18"
      ETHEREUM_PKEY: "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
      ALEPH_API_SERVER: http://pyaleph-api:4024
      ALEPH_CHANNEL: TEST
      FILTER_TAG: mainnet
      DB_PATH: /data/database
      BALANCES_SENDERS: '["0x70997970C51812dc3A010C7d01b50e0d17dc79C8"]'
      SCORES_SENDERS: '["0x70997970C51812dc3A010C7d01b50e0d17dc79C8"]'
      STATUS_SENDER: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
    depends_on:
      - anvil
      - pyaleph-api
    profiles:
      - nodestatus
    networks:
      - pyaleph
    logging:
      options:
        max-size: 50m

  scheduler-rs:
    restart: always
    image: ${SCHEDULER_RS_IMAGE}:${SCHEDULER_RS_TAG}
    depends_on:
      - redis
      - pyaleph-api
    environment:
      RUST_LOG: debug
      ALEPH_SCHEDULER_ALEPH_API_SERVER: http://pyaleph-api:4024
      ALEPH_SCHEDULER_CORECHANNEL_ADDRESS: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
      ALEPH_SCHEDULER_SKIP_HARDCODED_NODES: "true"
      ALEPH_SCHEDULER_NO_DISPATCH: "false"
      ALEPH_SCHEDULER_MIGRATIONS_ENABLED: "true"
      ALEPH_SCHEDULER_CRN_AUTH_TOKEN: "allocate-on-testnet"
      ALEPH_SCHEDULER_REDIS_URL: redis://redis:6379
      ALEPH_SCHEDULER_DATA_DIR: /app
    networks:
      - pyaleph
    profiles:
      - scheduler
    logging:
      options:
        max-size: 50m

  scheduler-api:
    restart: always
    image: ${SCHEDULER_API_IMAGE}:${SCHEDULER_API_TAG}
    depends_on:
      - redis
      - postgres
    environment:
      RUST_LOG: info
      SCHEDULER_API_ALEPH_API_SERVER: http://pyaleph-api:4024
      SCHEDULER_API_REDIS_URL: redis://redis:6379
      SCHEDULER_API_DATABASE_URL: postgres://aleph:decentralize-everything@postgres:5432/scheduler
      SCHEDULER_API_HOST: "0.0.0.0"
      SCHEDULER_API_PORT: "8082"
    ports:
      - "127.0.0.1:8082:8082"
    networks:
      - pyaleph
    profiles:
      - scheduler
    logging:
      options:
        max-size: 50m

networks:
  pyaleph:
