#!/usr/bin/env bash
# Provision and configure CRN (Compute Resource Node) instances on DigitalOcean.
#
# Usage:
#   ./scripts/crn-up.sh                    # full run: provision → install → register
#   ./scripts/crn-up.sh --provision        # create DO droplet, wait for SSH
#   ./scripts/crn-up.sh --install          # install aleph-vm .deb, configure, start
#   ./scripts/crn-up.sh --register         # register CRN in corechannel aggregate
#   ./scripts/crn-up.sh --status           # check CRN supervisor status
#   ./scripts/crn-up.sh --destroy          # delete droplet and clean state
#
# Environment variables:
#   CCN_URL             URL of the CCN API (required for --install, --register), e.g. http://1.2.3.4:4024
#   SSH_KEY_FILE        Path to SSH private key for droplet access (optional, defaults to ~/.ssh/id_ed25519)
#   DO_SSH_KEY_FINGERPRINT  SSH key fingerprint registered with DigitalOcean (required for --provision)
#   DO_REGION           DigitalOcean region (default: ams3)
#   DO_SIZE             Droplet size (default: s-8vcpu-16gb)
#   CRN_COUNT           Number of CRNs to provision (default: 1)
#   ALEPH_VM_VERSION    Override aleph-vm version from manifesto
#   ALEPH_VM_BRANCH     Deploy from a Git branch instead of a release (uses CI artifacts via gh CLI)
#
# CRN /control/allocations auth uses EIP-191 signatures: the scheduler signs
# requests with the key generated by local-up.sh --env, and CRNs resolve the
# authorized signer from the network settings aggregate (aleph-vm#968) instead
# of a per-CRN override — see publish-settings-aggregate.sh and the
# SETTINGS_AGGREGATE_ADDR constant below.
#
# State is stored in .local/crn/<index>/ (droplet-name, droplet-ip, crn-hash).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_DIR="$REPO_ROOT/.local"
BIN_DIR="$REPO_ROOT/bin"

# Defaults
SSH_KEY_FILE="${SSH_KEY_FILE:-$HOME/.ssh/id_ed25519}"
DO_REGION="${DO_REGION:-ams3}"
DO_SIZE="${DO_SIZE:-s-8vcpu-16gb}"
CRN_COUNT="${CRN_COUNT:-1}"

# Extract host from a URL, e.g. http://[::1]:4024 -> ::1, http://1.2.3.4:4024 -> 1.2.3.4
url_host() {
    python3 -c "from urllib.parse import urlparse; print(urlparse('$1').hostname)"
}

# Anvil account #4 — used for CRN registration (has 1M ALEPH from funding)
CRN_OWNER_KEY="0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a"
CRN_OWNER_ADDR="0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"

# Anvil account #2 — nodestatus writes the corechannel aggregate under this address
NODESTATUS_ADDR="0x70997970C51812dc3A010C7d01b50e0d17dc79C8"

# Anvil account #3 — settings-aggregate publisher (testnet stand-in for the
# foundation address owning the mainnet settings aggregate). CRNs read the
# Aleph-EIP191-V1 authorized signers from the `settings` aggregate at this
# address (aleph-vm#968); publish-settings-aggregate.sh writes it.
SETTINGS_AGGREGATE_ADDR="0x90F79bf6EB2c4f870365E785982E1f101E93b906"

# Network passed as --network on every CLI call. The CLI derives the corechannel
# --network-tag from this network's name, so it MUST match the nodestatus
# FILTER_TAG (deploy/docker-compose.yml) and the tests' --network (tests/conftest.py),
# otherwise nodestatus ignores the create/link operations.
TESTNET_NETWORK="testnet"

# Read aleph-vm version from manifesto (or use env override)
read_vm_version() {
    if [ -n "${ALEPH_VM_VERSION:-}" ]; then
        echo "$ALEPH_VM_VERSION"
        return
    fi
    python3 -c "
import yaml
with open('$REPO_ROOT/manifesto.yml') as f:
    m = yaml.safe_load(f)
print(m['components']['aleph-vm']['version'])
"
}

read_vm_connector_image() {
    python3 -c "
import yaml
with open('$REPO_ROOT/manifesto.yml') as f:
    m = yaml.safe_load(f)
c = m['infrastructure']['vm-connector']
print(f'{c[\"image\"]}:{c[\"tag\"]}')
"
}

# Read aleph-vm branch from manifesto (or use env override).
# Returns empty string if no branch is configured.
read_vm_branch() {
    if [ -n "${ALEPH_VM_BRANCH:-}" ]; then
        echo "$ALEPH_VM_BRANCH"
        return
    fi
    python3 -c "
import yaml
with open('$REPO_ROOT/manifesto.yml') as f:
    m = yaml.safe_load(f)
print(m['components']['aleph-vm'].get('branch', ''))
"
}

# Download aleph-vm .deb from GitHub Actions CI artifacts for a given branch.
# Requires the gh CLI to be installed and authenticated.
fetch_vm_deb_from_branch() {
    local branch="$1"
    local dest="$2"
    local repo="aleph-im/aleph-vm"
    local workflow="build-deb-package-and-integration-tests.yml"
    local artifact_name="aleph-vm.ubuntu-24.04.deb"

    if ! command -v gh &>/dev/null; then
        echo "ERROR: gh CLI is required to download CI artifacts. Install it from https://cli.github.com/" >&2
        return 1
    fi

    echo "==> Fetching .deb artifact for branch '$branch' from CI..."

    local run_id
    run_id=$(gh run list \
        --repo "$repo" \
        --branch "$branch" \
        --workflow "$workflow" \
        --status success \
        --limit 1 \
        --json databaseId \
        -q '.[0].databaseId')

    if [ -z "$run_id" ] || [ "$run_id" = "null" ]; then
        echo "ERROR: No successful CI run found for branch '$branch' in $repo" >&2
        echo "       Make sure the branch has a passing CI run (push to main or open PR)." >&2
        return 1
    fi

    echo "    Found CI run: https://github.com/$repo/actions/runs/$run_id"

    local tmp_dir
    tmp_dir=$(mktemp -d)
    gh run download "$run_id" \
        --repo "$repo" \
        --name "$artifact_name" \
        --dir "$tmp_dir"

    mv "$tmp_dir/$artifact_name" "$dest"
    rm -rf "$tmp_dir"
    echo "    Downloaded $dest"
}

crn_dir() {
    local idx="$1"
    echo "$LOCAL_DIR/crn/$idx"
}

crn_ip() {
    local idx="$1"
    cat "$(crn_dir "$idx")/droplet-ip"
}

crn_name() {
    local idx="$1"
    cat "$(crn_dir "$idx")/droplet-name"
}

# Per-CRN optional state files (written by the caller, e.g. the CI workflow):
#   ssh-user       SSH user for this CRN (default: root). A non-root user
#                  needs passwordless sudo; remote commands run via `sudo -n`.
#   static         CRN not managed by this script's lifecycle: --provision and
#                  --destroy skip it; --install skips base system packages and
#                  resets aleph-vm state (tee-reset.sh) before installing.
#   confidential   Enable confidential computing (AMD SEV) in supervisor.env.
crn_ssh_user() {
    local f
    f="$(crn_dir "$1")/ssh-user"
    if [ -f "$f" ]; then cat "$f"; else echo "root"; fi
}

crn_is_static() {
    [ -f "$(crn_dir "$1")/static" ]
}

crn_is_confidential() {
    [ -f "$(crn_dir "$1")/confidential" ]
}

# Fresh droplets intermittently reset SSH connections mid-handshake
# (kex_exchange_identification: Connection reset by peer), especially under
# the rapid bursts of short-lived connections this script makes. Mitigate
# on two fronts:
#  - ControlMaster multiplexing: one TCP connection per CRN, reused by all
#    ssh/scp calls, so only the first connection is exposed to the flake.
#  - retry_255: retry connection-level failures (ssh/scp exit code 255).
#    The remote commands used here are idempotent, so re-running is safe.
SSH_OPTS=(
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
    -o ControlMaster=auto -o ControlPath=/tmp/ssh-cm-crn-%r@%h-%p -o ControlPersist=600
)

retry_255() {
    local attempt rc
    for attempt in 1 2 3 4 5; do
        "$@" && return 0
        rc=$?
        [ "$rc" -ne 255 ] && return "$rc"
        echo "    SSH connection failed (attempt $attempt/5), retrying in 5s ..." >&2
        sleep 5
    done
    return 255
}

ssh_crn() {
    local idx="$1"; shift
    local ip user
    ip=$(crn_ip "$idx")
    user=$(crn_ssh_user "$idx")
    if [ "$user" = "root" ]; then
        retry_255 ssh "${SSH_OPTS[@]}" -i "$SSH_KEY_FILE" "root@$ip" "$@"
    else
        # Non-root: run the remote command through passwordless sudo.
        retry_255 ssh "${SSH_OPTS[@]}" -i "$SSH_KEY_FILE" "$user@$ip" \
            "sudo -n bash -c $(printf '%q' "$*")"
    fi
}

scp_to_crn() {
    local idx="$1"; shift
    local ip user
    ip=$(crn_ip "$idx")
    user=$(crn_ssh_user "$idx")
    # /tmp is writable by any user; privileged moves happen via ssh_crn.
    retry_255 scp "${SSH_OPTS[@]}" -i "$SSH_KEY_FILE" "$@" "$user@$ip:/tmp/"
}

# ---------------------------------------------------------------------------
# Phase 1: Provision DigitalOcean droplets
# ---------------------------------------------------------------------------
provision() {
    : "${DO_SSH_KEY_FINGERPRINT:?DO_SSH_KEY_FINGERPRINT must be set}"

    for idx in $(seq 0 $((CRN_COUNT - 1))); do
        if crn_is_static "$idx"; then
            echo "==> CRN $idx is static — skipping provisioning."
            continue
        fi
        local dir
        dir=$(crn_dir "$idx")
        mkdir -p "$dir"

        local name="testnets-crn-${idx}-$(date +%s)"
        echo "$name" > "$dir/droplet-name"

        echo "==> Creating droplet $name ..."
        doctl compute droplet create \
            --image ubuntu-24-04-x64 \
            --size "$DO_SIZE" \
            --region "$DO_REGION" \
            --ssh-keys "$DO_SSH_KEY_FINGERPRINT" \
            --tag-name testnets-crn \
            --enable-ipv6 \
            --wait \
            "$name"

        echo "==> Waiting for IP..."
        local ip=""
        for _ in $(seq 1 30); do
            ip=$(doctl compute droplet get "$name" --format PublicIPv4 --no-header 2>/dev/null || true)
            if [ -n "$ip" ]; then break; fi
            sleep 2
        done
        if [ -z "$ip" ]; then
            echo "ERROR: Could not get IP for $name"
            exit 1
        fi
        echo "$ip" > "$dir/droplet-ip"

        # Get the public IPv6 address (DO assigns a /64 when --enable-ipv6 is used)
        local ipv6=""
        for _ in $(seq 1 15); do
            ipv6=$(doctl compute droplet get "$name" --format PublicIPv6 --no-header 2>/dev/null || true)
            if [ -n "$ipv6" ]; then break; fi
            sleep 2
        done
        if [ -n "$ipv6" ]; then
            echo "$ipv6" > "$dir/droplet-ipv6"
            echo "    Droplet $name → $ip (IPv6: $ipv6)"
        else
            echo "    Droplet $name → $ip (no IPv6)"
        fi

        echo "==> Waiting for SSH on $ip ..."
        for _ in $(seq 1 30); do
            if ssh-keyscan -H "$ip" >> ~/.ssh/known_hosts 2>/dev/null; then
                break
            fi
            sleep 3
        done

        # Wait for cloud-init to finish
        ssh_crn "$idx" "cloud-init status --wait || true"
    done
    echo "==> All CRN droplets provisioned."
}

# ---------------------------------------------------------------------------
# Phase 2: Install aleph-vm .deb and configure
# ---------------------------------------------------------------------------
install_crn() {
    : "${CCN_URL:?CCN_URL must be set (e.g. http://1.2.3.4:4024)}"

    local connector_image
    connector_image=$(read_vm_connector_image)

    # EIP-191 allocation auth: CRNs resolve the authorized scheduler signer from
    # the network settings aggregate at SETTINGS_AGGREGATE_ADDR (published by
    # publish-settings-aggregate.sh), so no per-CRN signer config is written here.
    echo "==> CRN settings aggregate: $SETTINGS_AGGREGATE_ADDR"

    # Determine .deb source: branch (CI artifact) or version (GitHub release).
    # NB: the branch path fetches the ubuntu-24.04 CI artifact — all CRNs and the
    # static TEE server run Ubuntu 24.04, so the bundled Python native extensions
    # match. Releases ship one .deb per distro, picked per CRN below.
    local branch
    branch=$(read_vm_branch)
    local local_deb=""
    local version=""

    if [ -n "$branch" ]; then
        local_deb="$LOCAL_DIR/aleph-vm.ubuntu-24.04.deb"
        mkdir -p "$LOCAL_DIR"
        fetch_vm_deb_from_branch "$branch" "$local_deb"
        echo "    vm-connector: $connector_image"
        echo "    CCN: $CCN_URL"
    else
        version=$(read_vm_version)
        echo "==> aleph-vm version: $version"
        echo "    vm-connector: $connector_image"
        echo "    CCN: $CCN_URL"
    fi

    for idx in $(seq 0 $((CRN_COUNT - 1))); do
        local ip
        ip=$(crn_ip "$idx")
        echo ""
        echo "==> Installing CRN on $(crn_name "$idx") ($ip) ..."

        # Build supervisor.env
        local env_file
        env_file=$(crn_dir "$idx")/supervisor.env
        # No local AUTHORIZED_ALLOCATION_SIGNERS override: the supervisor sources
        # the Aleph-EIP191-V1 signers from the settings aggregate published at
        # SETTINGS_AGGREGATE_ADDRESS (aleph-vm#968).
        cat > "$env_file" <<EOF
ALEPH_VM_SUPERVISOR_HOST=0.0.0.0
ALEPH_VM_DOMAIN_NAME=$ip
ALEPH_VM_API_SERVER=$CCN_URL
ALEPH_VM_OWNER_ADDRESS=$CRN_OWNER_ADDR
ALEPH_VM_SETTINGS_AGGREGATE_ADDRESS=$SETTINGS_AGGREGATE_ADDR
ALEPH_VM_PROGRAM_MEMORY_RESERVED_MIB=0
EOF

        # Static CRNs have no DO-provided IPv6 state file; detect the host's
        # global IPv6 over SSH. Without an ALEPH_VM_IPV6_ADDRESS_POOL the
        # scheduler refuses to place *any* instance on the node (it requires
        # a public /64 pool), confidential ones included.
        local ipv6_file
        ipv6_file=$(crn_dir "$idx")/droplet-ipv6
        if crn_is_static "$idx" && [ ! -f "$ipv6_file" ]; then
            local detected_ipv6
            detected_ipv6=$(ssh_crn "$idx" "ip -6 addr show scope global" 2>/dev/null \
                | sed -n 's/.*inet6 \([0-9a-f:]*\)\/.*/\1/p' \
                | grep -v '^f[cd]' | head -1 || true)
            if [ -n "$detected_ipv6" ]; then
                echo "$detected_ipv6" > "$ipv6_file"
                echo "    Detected IPv6: $detected_ipv6"
            else
                echo "    WARNING: no global IPv6 on static CRN — the scheduler will not place instances on it"
            fi
        fi

        # Configure IPv6 if the CRN has a public IPv6 address
        if [ -f "$ipv6_file" ]; then
            local ipv6_addr
            ipv6_addr=$(cat "$ipv6_file")
            # Derive the /64 prefix from the assigned address
            local ipv6_pool
            ipv6_pool=$(python3 -c "import ipaddress; print(ipaddress.IPv6Network(('$ipv6_addr', 64), strict=False))")
            cat >> "$env_file" <<EOF
ALEPH_VM_IPV6_ADDRESS_POOL=$ipv6_pool
ALEPH_VM_IPV6_ALLOCATION_POLICY=dynamic
EOF
            echo "    IPv6 pool: $ipv6_pool"
        fi

        # If we already have a node hash from registration, include it
        local hash_file
        hash_file=$(crn_dir "$idx")/crn-hash
        if [ -f "$hash_file" ]; then
            echo "ALEPH_VM_NODE_HASH=$(cat "$hash_file")" >> "$env_file"
        fi

        # Confidential computing (AMD SEV) support
        if crn_is_confidential "$idx"; then
            cat >> "$env_file" <<EOF
ALEPH_VM_ENABLE_CONFIDENTIAL_COMPUTING=true
ALEPH_VM_SEV_CTL_PATH=/opt/sevctl
EOF
            echo "    Confidential computing: enabled"
        fi

        # Copy config (via /tmp: the SSH user may not be root)
        scp_to_crn "$idx" "$env_file"
        ssh_crn "$idx" "mkdir -p /etc/aleph-vm && mv /tmp/supervisor.env /etc/aleph-vm/supervisor.env"

        if crn_is_static "$idx"; then
            # Static server: base packages are one-time provisioning
            # (docs/tee-server.md). Reset leftover aleph-vm state from
            # previous CI runs instead of upgrading the box.
            echo "    Static CRN: skipping base packages, resetting aleph-vm state..."
            "$REPO_ROOT/scripts/tee-reset.sh" "$ip" "$(crn_ssh_user "$idx")" "$SSH_KEY_FILE"
        else
            # Wait for apt lock
            ssh_crn "$idx" "while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 2; done"

            # System update + dependencies
            echo "    Installing system packages..."
            # NEEDRESTART_SUSPEND stops needrestart from bouncing sshd after the
            # upgrade, which would reset the next SSH connection mid-handshake.
            ssh_crn "$idx" "NEEDRESTART_SUSPEND=1 DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=-1 update"
            ssh_crn "$idx" "NEEDRESTART_SUSPEND=1 DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=-1 upgrade -y"
            ssh_crn "$idx" "NEEDRESTART_SUSPEND=1 DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=-1 install -y docker.io apparmor-profiles"
        fi

        # Start vm-connector. Remove any existing container first so a static
        # server picks up vm-connector image updates between runs.
        echo "    Starting vm-connector..."
        ssh_crn "$idx" "docker pull $connector_image"
        ssh_crn "$idx" "docker rm -f vm-connector 2>/dev/null || true"
        ssh_crn "$idx" "docker run -d -p 127.0.0.1:4021:4021/tcp --restart=always --name vm-connector $connector_image"

        # Download/upload and install .deb
        if [ -n "$local_deb" ]; then
            echo "    Uploading aleph-vm .deb..."
            scp_to_crn "$idx" "$local_deb"
            ssh_crn "$idx" "mv /tmp/$(basename "$local_deb") /opt/aleph-vm.deb"
        else
            # Pick the release .deb matching this CRN's distro (e.g. a static
            # TEE server may not run debian-12 like the DO droplets do).
            local deb_variant
            deb_variant=$(ssh_crn "$idx" '. /etc/os-release && echo "${ID}-${VERSION_ID}"' 2>/dev/null || true)
            deb_variant="${deb_variant:-ubuntu-24.04}"
            local deb_url="https://github.com/aleph-im/aleph-vm/releases/download/${version}/aleph-vm.${deb_variant}.deb"
            echo "    Downloading aleph-vm ${version} (${deb_variant})..."
            ssh_crn "$idx" "wget -q -O /opt/aleph-vm.deb '$deb_url'"
        fi
        echo "    Installing .deb..."
        # --reinstall: on a static CRN the same package version may already be
        # installed (possibly from a different distro's .deb, which leaves the
        # bundled Python packages broken) — plain `install` would skip it.
        # --allow-downgrades: the .deb version is `git describe` (commits since
        # the last tag), so a rebased branch can have a *lower* count than the
        # .deb left on the static box by a previous run (e.g. a long pre-squash
        # branch). apt treats that as a downgrade and aborts without this flag.
        ssh_crn "$idx" "NEEDRESTART_SUSPEND=1 DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=-1 -o Dpkg::Options::=--force-confold install --reinstall --allow-downgrades -y /opt/aleph-vm.deb"

        # Wait for supervisor to be active
        echo "    Waiting for CRN supervisor..."
        local ready=false
        for _ in $(seq 1 30); do
            if ssh_crn "$idx" "systemctl is-active aleph-vm-supervisor.service" 2>/dev/null | grep -q "^active$"; then
                ready=true
                break
            fi
            sleep 5
        done

        if $ready; then
            echo "    CRN supervisor is running on $ip"
        else
            echo "    WARNING: CRN supervisor not active after 150s — check logs"
            ssh_crn "$idx" "systemctl status aleph-vm-supervisor.service" || true
        fi
    done
    echo ""
    echo "==> All CRNs installed."
}

# ---------------------------------------------------------------------------
# Phase 3: Register CRN in corechannel aggregate
# ---------------------------------------------------------------------------
register_crn() {
    : "${CCN_URL:?CCN_URL must be set (e.g. http://1.2.3.4:4024)}"

    local aleph_cli="$BIN_DIR/aleph"
    if [ ! -x "$aleph_cli" ]; then
        echo "ERROR: aleph CLI not found at $aleph_cli — run local-up.sh --env first"
        exit 1
    fi

    local ccn_url="$CCN_URL"
    local err_log
    err_log=$(mktemp)

    # Ensure the CLI has a 'testnet' network so `--network testnet` resolves
    # (and so node operations are tagged 'testnet', matching nodestatus's
    # FILTER_TAG). Idempotent: add if missing, otherwise refresh its scheduler
    # URL. The scheduler URL is unused here but kept local so the network never
    # points at mainnet infrastructure.
    "$aleph_cli" config network add "$TESTNET_NETWORK" --scheduler-url "http://localhost:8082" 2>/dev/null \
        || "$aleph_cli" config network set --network "$TESTNET_NETWORK" --scheduler-url "http://localhost:8082" >/dev/null 2>&1
    "$aleph_cli" config network use "$TESTNET_NETWORK" >/dev/null 2>&1

    # Ensure a CCN exists in the corechannel aggregate (required before linking CRNs).
    # The link operation looks up a CCN owned by the same sender account.
    # The corechannel aggregate is written by nodestatus under NODESTATUS_ADDR,
    # not under the sender's address.  Filter nodes by owner to find ours.
    echo "==> Ensuring CCN exists for owner $CRN_OWNER_ADDR ..."
    local ccn_nodes
    ccn_nodes=$("$aleph_cli" --ccn "$ccn_url" --network "$TESTNET_NETWORK" --json node list \
        --type ccn --address "$CRN_OWNER_ADDR" --corechannel-address "$NODESTATUS_ADDR" \
        2>/dev/null | jq -r 'length' 2>/dev/null || echo "0")
    if [ "$ccn_nodes" = "0" ]; then
        echo "    No CCN found — creating one..."
        ALEPH_PRIVATE_KEY="$CRN_OWNER_KEY" "$aleph_cli" \
            --ccn "$ccn_url" --network "$TESTNET_NETWORK" \
            node create-ccn \
            "testnet-ccn" \
            --multiaddress "$(ccn_host=$(url_host "$CCN_URL"); if [[ "$ccn_host" == *:* ]]; then echo "/ip6/$ccn_host/tcp/4025/p2p/testnet"; else echo "/ip4/$ccn_host/tcp/4025/p2p/testnet"; fi)" \
            --chain eth \
            2>"$err_log" || {
            echo "    WARNING: create-ccn failed: $(cat "$err_log")"
        }
        # Wait for nodestatus to process the CCN creation
        echo "    Waiting for CCN to appear in corechannel aggregate..."
        for _ in $(seq 1 24); do
            ccn_nodes=$("$aleph_cli" --ccn "$ccn_url" --network "$TESTNET_NETWORK" --json node list \
                --type ccn --address "$CRN_OWNER_ADDR" --corechannel-address "$NODESTATUS_ADDR" \
                2>/dev/null | jq -r 'length' 2>/dev/null || echo "0")
            if [ "$ccn_nodes" != "0" ]; then
                echo "    CCN is registered."
                break
            fi
            sleep 5
        done
    else
        echo "    CCN already exists."
    fi

    for idx in $(seq 0 $((CRN_COUNT - 1))); do
        local ip
        ip=$(crn_ip "$idx")
        local crn_name_str="testnet-crn-$idx"

        # Register with IPv4 — the scheduler and tests must be able to reach
        # this address.  IPv6 *capability* is advertised separately via the
        # CRN's ALEPH_VM_IPV6_ADDRESS_POOL in supervisor.env.
        local crn_addr="http://$ip:4020"

        echo "==> Registering CRN $crn_name_str ($crn_addr) ..."

        # Create resource node
        local output
        output=$(ALEPH_PRIVATE_KEY="$CRN_OWNER_KEY" "$aleph_cli" \
            --ccn "$ccn_url" --network "$TESTNET_NETWORK" --json \
            node create-crn \
            "$crn_name_str" \
            --url "$crn_addr" \
            --chain eth 2>"$err_log") || {
            echo "    create-crn failed: $(cat "$err_log")"
            echo "    (This may fail if the account lacks ALEPH balance)"
            continue
        }

        # Extract item_hash from the response
        local crn_hash
        crn_hash=$(echo "$output" | jq -r '.item_hash // empty' 2>/dev/null || true)
        if [ -z "$crn_hash" ]; then
            echo "    Could not extract item_hash from create-crn response."
            echo "    Response: $output"
            echo "    Trying to find node hash from corechannel aggregate..."

            # Fallback: look up the CRN in the corechannel aggregate by address
            crn_hash=$("$aleph_cli" --ccn "$ccn_url" --network "$TESTNET_NETWORK" --json node list \
                --type crn --all --corechannel-address "$NODESTATUS_ADDR" \
                2>/dev/null | jq -r ".[] | select(.address == \"$crn_addr\") | .hash" 2>/dev/null || true)
        fi

        if [ -z "$crn_hash" ]; then
            echo "    ERROR: Could not determine CRN hash. Skipping link step."
            continue
        fi

        echo "    CRN hash: $crn_hash"
        echo "$crn_hash" > "$(crn_dir "$idx")/crn-hash"

        # Link CRN to CCN
        echo "    Linking CRN to CCN..."
        ALEPH_PRIVATE_KEY="$CRN_OWNER_KEY" "$aleph_cli" \
            --ccn "$ccn_url" --network "$TESTNET_NETWORK" \
            node link --crn "$crn_hash" --chain eth 2>"$err_log" || {
            echo "    WARNING: link failed: $(cat "$err_log")"
        }

        # Update supervisor.env with node hash
        echo "    Setting ALEPH_VM_NODE_HASH on CRN..."
        ssh_crn "$idx" "grep -q ALEPH_VM_NODE_HASH /etc/aleph-vm/supervisor.env && \
            sed -i 's/^ALEPH_VM_NODE_HASH=.*/ALEPH_VM_NODE_HASH=$crn_hash/' /etc/aleph-vm/supervisor.env || \
            echo 'ALEPH_VM_NODE_HASH=$crn_hash' >> /etc/aleph-vm/supervisor.env"
        ssh_crn "$idx" "systemctl restart aleph-vm-supervisor.service"

        echo "    CRN $crn_name_str registered and linked."
    done
    rm -f "$err_log"
    echo ""
    echo "==> CRN registration complete."
}

# ---------------------------------------------------------------------------
# Status check
# ---------------------------------------------------------------------------
status_crn() {
    for idx in $(seq 0 $((CRN_COUNT - 1))); do
        local dir
        dir=$(crn_dir "$idx")
        if [ ! -f "$dir/droplet-ip" ]; then
            echo "CRN $idx: not provisioned"
            continue
        fi
        local ip
        ip=$(crn_ip "$idx")
        local name
        name=$(crn_name "$idx")
        echo "CRN $idx: $name ($ip)"

        # Check supervisor status
        local active
        active=$(ssh_crn "$idx" "systemctl is-active aleph-vm-supervisor.service" 2>/dev/null || echo "unknown")
        echo "    Supervisor: $active"

        # Check /about/usage/system endpoint
        local usage
        usage=$(ssh_crn "$idx" "curl -sf http://localhost:4020/about/usage/system" 2>/dev/null || echo "{}")
        echo "    Usage: $usage"

        # Check registration
        if [ -f "$dir/crn-hash" ]; then
            echo "    Node hash: $(cat "$dir/crn-hash")"
        else
            echo "    Node hash: not registered"
        fi
        echo ""
    done
}

# ---------------------------------------------------------------------------
# Destroy
# ---------------------------------------------------------------------------
destroy() {
    # Iterate over all existing CRN state directories, regardless of CRN_COUNT,
    # to avoid leaking droplets if count changed between provision and destroy.
    if [ ! -d "$LOCAL_DIR/crn" ]; then
        echo "==> No CRN state found."
        return
    fi
    for dir in "$LOCAL_DIR/crn"/*/; do
        [ -d "$dir" ] || continue
        if [ -f "$dir/static" ]; then
            echo "==> Skipping static CRN state in $dir (not ours to destroy)."
            continue
        fi
        if [ -f "$dir/droplet-name" ]; then
            local name
            name=$(cat "$dir/droplet-name")
            echo "==> Deleting droplet $name ..."
            doctl compute droplet delete --force "$name" 2>/dev/null || true
        fi
        rm -rf "$dir"
    done
    echo "==> CRN droplets destroyed."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
case "${1:-}" in
    --provision)
        provision
        ;;
    --install)
        install_crn
        ;;
    --register)
        register_crn
        ;;
    --status)
        status_crn
        ;;
    --destroy)
        destroy
        ;;
    "")
        provision
        install_crn
        register_crn
        ;;
    --help|-h)
        echo "Usage: $0 [--provision|--install|--register|--status|--destroy]"
        exit 0
        ;;
    *)
        echo "Usage: $0 [--provision|--install|--register|--status|--destroy]"
        exit 1
        ;;
esac
