#!/usr/bin/env bash
# Publish the network settings aggregate that CRNs use to resolve the
# Aleph-EIP191-V1 authorized allocation signers (aleph-vm#968).
#
# Each CRN fetches
#   {API_SERVER}/api/v0/aggregates/<SETTINGS_AGGREGATE_ADDRESS>.json?keys=settings
# and trusts the addresses in settings.authorized_allocation_signers. We publish
# that aggregate here with the scheduler's dynamically-generated EIP-191 signer
# address (.local/crn-signer.env), so CRNs learn the testnet scheduler key from
# the network instead of from a per-CRN env override. This is what crn-up.sh
# points ALEPH_VM_SETTINGS_AGGREGATE_ADDRESS at.
#
# Environment variables:
#   CCN_URL   CCN API base URL (default: http://localhost:4024)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_DIR="$REPO_ROOT/.local"
BIN_DIR="$REPO_ROOT/bin"
CCN_URL="${CCN_URL:-http://localhost:4024}"

# Network passed as --network so the CLI never falls back to its builtin
# mainnet network. Must match crn-up.sh / tests (see crn-up.sh for rationale).
TESTNET_NETWORK="testnet"

# Anvil account #3 — dedicated settings-aggregate publisher: the testnet's
# stand-in for the foundation address that owns the mainnet settings aggregate.
# Its address is what CRNs point SETTINGS_AGGREGATE_ADDRESS at (crn-up.sh keeps
# the same constant). Aggregate messages are free, so it needs no balance.
PUBLISHER_ADDR="0x90F79bf6EB2c4f870365E785982E1f101E93b906"
PUBLISHER_KEY="0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"

ALEPH_CLI="$BIN_DIR/aleph"
if [ ! -x "$ALEPH_CLI" ]; then
    echo "ERROR: aleph CLI not found at $ALEPH_CLI — run local-up.sh --env first" >&2
    exit 1
fi

# The scheduler's EIP-191 signer address, generated by local-up.sh --env.
signer_addr=$(grep '^CRN_SIGNER_ADDRESS=' "$LOCAL_DIR/crn-signer.env" 2>/dev/null | cut -d= -f2)
if [ -z "$signer_addr" ]; then
    echo "ERROR: no CRN signer address in $LOCAL_DIR/crn-signer.env — run local-up.sh --env first" >&2
    exit 1
fi

echo "==> Publishing settings aggregate (publisher $PUBLISHER_ADDR, signer $signer_addr) ..."

# Ensure the 'testnet' network exists so `--network testnet` resolves. Idempotent:
# add if missing, otherwise refresh. The scheduler URL is unused for an aggregate
# post but kept local so the network never points at mainnet infrastructure.
"$ALEPH_CLI" config network add "$TESTNET_NETWORK" --scheduler-url "http://localhost:8082" 2>/dev/null \
    || "$ALEPH_CLI" config network set --network "$TESTNET_NETWORK" --scheduler-url "http://localhost:8082" >/dev/null 2>&1 \
    || true

content=$(printf '{"authorized_allocation_signers": ["%s"]}' "$signer_addr")

ALEPH_PRIVATE_KEY="$PUBLISHER_KEY" "$ALEPH_CLI" \
    --ccn "$CCN_URL" --network "$TESTNET_NETWORK" \
    aggregate create --key settings --content "$content" --channel TEST --chain eth

# Verify it is readable the same way the CRN reads it.
echo "==> Verifying settings aggregate is readable ..."
want=$(echo "$signer_addr" | tr '[:upper:]' '[:lower:]')
for _ in $(seq 1 12); do
    got=$(curl -sf "$CCN_URL/api/v0/aggregates/$PUBLISHER_ADDR.json?keys=settings" 2>/dev/null \
        | jq -r '.data.settings.authorized_allocation_signers[0] // empty' 2>/dev/null \
        | tr '[:upper:]' '[:lower:]' || true)
    if [ "$got" = "$want" ]; then
        echo "    Settings aggregate published and verified at $PUBLISHER_ADDR."
        exit 0
    fi
    sleep 5
done

echo "ERROR: settings aggregate did not become readable with the expected signer within 60s" >&2
exit 1
